### ISSUE TITLE
Security: Signing certificate URL should be validated

### ISSUE THREAD

**Issue by kegsay** [robbiet480/go.sns#2]
This code currently has a security vulnerability which allows an attacker to impersonate official AWS SNS requests.

The problem lies with how the payload is verified. An attacker can control the payload but this is supposed to be fine because the signature check will fail. This check, however, relies on `SigningCertURL` which is *included in the payload*, which is under the attacker's control. A malicious entity could point this URL to a valid certificate which was used to sign the malicious payload and this code will currently accept that.

It's unfortunate that the SNS API makes it really easy to footgun yourself here because it includes `SigningCertURL` as a key in the payload which is attacker controlled. This heavily encourages users to blindly use this URL to retrieve the certificate which is then used to verify the payload.

What's worse, the [official AWS SNS docs for verifying payloads](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.verify.signature.html) does not mention this, but [this thread](https://forums.aws.amazon.com/thread.jspa?threadID=61366) alludes to the problem. Interestingly, the [official SNS validator for Node](https://github.com/aws/aws-js-sns-message-validator/blob/ae795b3b342137ea1e783c57140191e5ae48ab16/index.js#L7) does include a hostname check on the `SigningCertURL`: we should be doing the same.

**Comment by robbiet480** [comment]
Thanks for this @Kegsay! Mind submitting a PR for this, as I am no longer actively using the library?

**Comment by kegsay** [comment]
Sure, will link to this issue when I've done so.
